### ISSUE TITLE
The mathematical formula reported an error

### ISSUE THREAD

**Issue by linjialiang** [AtomLinter/linter-markdown#215]
> The mathematical formula reported an error
![图片](https://user-images.githubusercontent.com/8848263/54580720-6ab52a00-4a44-11e9-96ca-4e667f975e79.png)

**Comment by Arcanemagus** [comment]
Issues with the results themselves should be reported to the linter: [remark-lint](https://github.com/remarkjs/remark-lint/issues)

This package is just a translation layer between that and Atom 😉.

**Comment by wooorm** [comment]
It’s not an issue with remark-lint either!

Math is a non-standard extension to markdown. remark does extensions through plugins, for example you would want to use [remark-math](https://github.com/Rokt33r/remark-math).

If you want to use plugins, you can use [linter-remark](https://github.com/wooorm/linter-remark) in combination with remark-math and remark-lint, instead of this project, linter-markdown.

**Comment by linjialiang** [comment]
ok
